version: '2'
networks:
    default:
        external:
            name: local
services:
    rabbit:
        container_name: rabbit
        image: rabbitmq:3.6-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - ./data/rabbitmq-mnesia:/var/lib/rabbitmq/mnesia/
        expose:
            - 5672
            - 15672
            - 12397
        ports:
            - "5672:5672"
            - "15672:15672"
    chat2speech:
        container_name: chat2speech-app
        image: khilnani/pythonlite:latest
        depends_on:
            - rabbit
        restart: always
        environment:
            - ENV=production
            - PORT=8888
            - RABBITMQ_USER=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_HOST=rabbit
            - RABBITMQ_VHOST=/
        volumes:
            - .:/opt/chat2speech
        expose:
            - 8888
            - 5000
        ports:
            - "8888:8888"
        entrypoint: /bin/sh /opt/chat2speech/env/entrypoint-app.sh
